# Generated by Django 5.0.6 on 2024-05-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('Location', models.CharField(max_length=256)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.designation')),
            ],
        ),
    ]
